# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 


[colors]
[colors.primary]
background = "#000000"
foreground = "#bf9b6f"

[colors.normal]
black   = "#000000"
red     = "#d94b18"
green   = "#d98b48"
yellow  = "#f29d35"
blue    = "#f28a2e"
magenta = "#1f4e5b"
cyan    = "#bf6341"
white   = "#bf9b6f"

[colors.bright]
black   = "#4a2d30"
red     = "#d94b18"
green   = "#d98b48"
yellow  = "#f29d35"
blue    = "#f28a2e"
magenta = "#49afc4"
cyan    = "#bf6341"
white   = "#f2e85c"

[colors.cursor]
text   = "#000000"
cursor = "#bf9b6f"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
