#                                                                    
#                                                                    
# ,gggggggggggg,    ,ggg,         gg  ,ggg, ,ggggggg,     ,ggggggg,  
# dP"""88""""""Y8b, dP""Y8a        88 dP""Y8,8P"""""Y8b  ,dP""""""Y8b
# Yb,  88       `8b,Yb, `88        88 Yb, `8dP'     `88  d8'    a  Y8
#  `"  88        `8b `"  88        88  `"  88'       88  88     "Y8P'
#      88         Y8     88        88      88        88  `8baaaa     
#      88         d8     88        88      88        88 ,d8P""""     
#      88        ,8P     88        88      88        88 d8"          
#      88       ,8P'     88        88      88        88 Y8,          
#      88______,dP'      Y8b,____,d88,     88        Y8,`Yba,,_____, 
#     888888888P"         "Y888888P"Y8     88        `Y8  `"Y8888888 
#                                                                    
#                                                                    
#                                                                    
#                                                                    

# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 

[window]
opacity = 0.93

[colors]
transparent_background_colors = false

[colors.primary]
background = "#120d0a"
foreground = "#d1b38a"

[colors.normal]
black   = "#120d0a"
red     = "#8e2f22"
green   = "#7f6a46"
yellow  = "#b88a42"
blue    = "#c86a24"
magenta = "#3c8f95"
cyan    = "#8a5e3b"
white   = "#d1b38a"

[colors.bright]
black   = "#403026"
red     = "#b24a22"
green   = "#9a8457"
yellow  = "#d2a25a"
blue    = "#e08a2e"
magenta = "#58b8c2"
cyan    = "#a87448"
white   = "#f0ddba"

[colors.cursor]
text   = "#120d0a"
cursor = "#d1b38a"

[colors.selection]
text = "#e08a2e"
background = "#403026"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#

# ░░      ░░░  ░░░░░░░░       ░░                              
# ▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒                              
# ▓  ▓▓▓▓  ▓▓  ▓▓▓▓▓▓▓▓  ▓▓▓▓  ▓                              
# █  ████  ██  ████████  ████  █                              
# ██      ███        ██       ██                              
#                                                             
# ░        ░░░      ░░░       ░░░░      ░░░       ░░░░      ░░
# ▒▒▒▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒
# ▓▓▓▓▓▓▓  ▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓
# █  ████  ██  ████  ██  ████  ██  ████  ██  ████  ██  ████  █
# ██      ████      ███       ████      ███       ████      ██
#                                                             
