# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[colors-dark]
foreground=bf9b6f
background=000000
alpha=0.888
cursor=000000 bf9b6f
selection-foreground=000000
selection-background=f28a2e

regular0=000000
regular1=d94b18
regular2=d98b48
regular3=f29d35
regular4=f28a2e
regular5=1f4e5b
regular6=bf6341
regular7=bf9b6f

bright0=4a2d30
bright1=d94b18
bright2=d98b48
bright3=f29d35
bright4=f28a2e
bright5=49afc4
bright6=bf6341
bright7=f2e85c
