#                                                                    
#                                                                    
# ,gggggggggggg,    ,ggg,         gg  ,ggg, ,ggggggg,     ,ggggggg,  
# dP"""88""""""Y8b, dP""Y8a        88 dP""Y8,8P"""""Y8b  ,dP""""""Y8b
# Yb,  88       `8b,Yb, `88        88 Yb, `8dP'     `88  d8'    a  Y8
#  `"  88        `8b `"  88        88  `"  88'       88  88     "Y8P'
#      88         Y8     88        88      88        88  `8baaaa     
#      88         d8     88        88      88        88 ,d8P""""     
#      88        ,8P     88        88      88        88 d8"          
#      88       ,8P'     88        88      88        88 Y8,          
#      88______,dP'      Y8b,____,d88,     88        Y8,`Yba,,_____, 
#     888888888P"         "Y888888P"Y8     88        `Y8  `"Y8888888 
#                                                                    
#                                                                    
#                                                                    
#                                                                    

# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[colors-dark]
foreground=d1b38a
background=120d0a
alpha=0.93
cursor=120d0a d1b38a
selection-foreground=e08a2e
selection-background=3a2a20

regular0=120d0a
regular1=8e2f22
regular2=7f6a46
regular3=b88a42
regular4=c86a24
regular5=3c8f95
regular6=8a5e3b
regular7=d1b38a

bright0=3a2a20
bright1=b24a22
bright2=9a8457
bright3=d2a25a
bright4=e08a2e
bright5=58b8c2
bright6=a87448
bright7=f0ddba

# ░░      ░░░  ░░░░░░░░       ░░                              
# ▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒                              
# ▓  ▓▓▓▓  ▓▓  ▓▓▓▓▓▓▓▓  ▓▓▓▓  ▓                              
# █  ████  ██  ████████  ████  █                              
# ██      ███        ██       ██                              
#                                                             
# ░        ░░░      ░░░       ░░░░      ░░░       ░░░░      ░░
# ▒▒▒▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒
# ▓▓▓▓▓▓▓  ▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓
# █  ████  ██  ████  ██  ████  ██  ████  ██  ████  ██  ████  █
# ██      ████      ███       ████      ███       ████      ██
#                                                             