#                                                                    
#                                                                    
# ,gggggggggggg,    ,ggg,         gg  ,ggg, ,ggggggg,     ,ggggggg,  
# dP"""88""""""Y8b, dP""Y8a        88 dP""Y8,8P"""""Y8b  ,dP""""""Y8b
# Yb,  88       `8b,Yb, `88        88 Yb, `8dP'     `88  d8'    a  Y8
#  `"  88        `8b `"  88        88  `"  88'       88  88     "Y8P'
#      88         Y8     88        88      88        88  `8baaaa     
#      88         d8     88        88      88        88 ,d8P""""     
#      88        ,8P     88        88      88        88 d8"          
#      88       ,8P'     88        88      88        88 Y8,          
#      88______,dP'      Y8b,____,d88,     88        Y8,`Yba,,_____, 
#     888888888P"         "Y888888P"Y8     88        `Y8  `"Y8888888 
#                                                                    
#                                                                    
#                                                                    
#                                                                    

# ghostty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 


# Background and foreground colors
background = #120d0a
foreground = #d1b38a
selection-background = #403026
selection-foreground = #e08a2e

# Standard colors
palette = 0=#120d0a
palette = 1=#8e2f22
palette = 2=#7f6a46
palette = 3=#b88a42
palette = 4=#c86a24
palette = 5=#3c8f95
palette = 6=#8a5e3b
palette = 7=#d1b38a

# Bright colors
palette = 8=#403026
palette = 9=#b24a22
palette = 10=#9a8457
palette = 11=#d2a25a
palette = 12=#e08a2e
palette = 13=#58b8c2
palette = 14=#a87448
palette = 15=#f0ddba

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  

# ░░      ░░░  ░░░░░░░░       ░░                              
# ▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒                              
# ▓  ▓▓▓▓  ▓▓  ▓▓▓▓▓▓▓▓  ▓▓▓▓  ▓                              
# █  ████  ██  ████████  ████  █                              
# ██      ███        ██       ██                              
#                                                             
# ░        ░░░      ░░░       ░░░░      ░░░       ░░░░      ░░
# ▒▒▒▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒
# ▓▓▓▓▓▓▓  ▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓
# █  ████  ██  ████  ██  ████  ██  ████  ██  ████  ██  ████  █
# ██      ████      ███       ████      ███       ████      ██
#                                                             
