#                                                                    
#                                                                    
# ,gggggggggggg,    ,ggg,         gg  ,ggg, ,ggggggg,     ,ggggggg,  
# dP"""88""""""Y8b, dP""Y8a        88 dP""Y8,8P"""""Y8b  ,dP""""""Y8b
# Yb,  88       `8b,Yb, `88        88 Yb, `8dP'     `88  d8'    a  Y8
#  `"  88        `8b `"  88        88  `"  88'       88  88     "Y8P'
#      88         Y8     88        88      88        88  `8baaaa     
#      88         d8     88        88      88        88 ,d8P""""     
#      88        ,8P     88        88      88        88 d8"          
#      88       ,8P'     88        88      88        88 Y8,          
#      88______,dP'      Y8b,____,d88,     88        Y8,`Yba,,_____, 
#     888888888P"         "Y888888P"Y8     88        `Y8  `"Y8888888 
#                                                                    
#                                                                    
#                                                                    
#                                                                    

# hyprlock.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

$color = rgba(18, 13, 10, 1)
$inner_color = rgba(26, 20, 16, 0.82)
$outer_color = rgba(168, 116, 72, 1)
$font_color = rgba(209, 179, 138, 1)
$placeholder_color = rgba(143, 118, 93, 0.72)
$check_color = rgba(200, 106, 36, 1)

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  

# ░░      ░░░  ░░░░░░░░       ░░                              
# ▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒                              
# ▓  ▓▓▓▓  ▓▓  ▓▓▓▓▓▓▓▓  ▓▓▓▓  ▓                              
# █  ████  ██  ████████  ████  █                              
# ██      ███        ██       ██                              
#                                                             
# ░        ░░░      ░░░       ░░░░      ░░░       ░░░░      ░░
# ▒▒▒▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒
# ▓▓▓▓▓▓▓  ▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓  ▓
# █  ████  ██  ████  ██  ████  ██  ████  ██  ████  ██  ████  █
# ██      ████      ███       ████      ███       ████      ██
#                                                             