local M = {}

function M.get(c, opts)
  opts = opts or {}

  return {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_float },
    FloatBorder = { fg = c.border, bg = c.bg_float },
    FloatTitle = { fg = c.accent, bg = c.bg_float, bold = true },
    Cursor = { fg = c.selection_fg, bg = c.cursor },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorColumn = { bg = c.bg_alt },
    CursorLine = { bg = c.bg_alt },
    CursorLineNr = { fg = c.accent, bg = c.bg_alt, bold = true },
    ColorColumn = { bg = c.bg_alt },
    Conceal = { fg = c.comment_alt },
    CurSearch = { fg = c.selection_fg, bg = c.yellow, bold = true },
    Directory = { fg = c.accent },
    EndOfBuffer = { fg = c.bg_dark },
    ErrorMsg = { fg = c.red, bg = c.bg },
    FoldColumn = { fg = c.comment, bg = c.bg },
    Folded = { fg = c.comment_alt, bg = c.bg_alt },
    IncSearch = { fg = c.selection_fg, bg = c.accent, bold = true },
    LineNr = { fg = c.comment, bg = c.bg },
    MatchParen = { fg = c.fg_bright, bg = c.bg_alt, bold = true },
    ModeMsg = { fg = c.green, bold = true },
    MoreMsg = { fg = c.green },
    NonText = { fg = c.border },
    Pmenu = { fg = c.fg, bg = c.bg_popup },
    PmenuSel = { fg = c.selection_fg, bg = c.selection_bg, bold = true },
    PmenuSbar = { bg = c.bg_alt },
    PmenuThumb = { bg = c.border },
    Question = { fg = c.accent },
    QuickFixLine = { bg = c.bg_alt, bold = true },
    Search = { fg = c.selection_fg, bg = c.selection_bg },
    SignColumn = { fg = c.comment, bg = c.bg },
    SpecialKey = { fg = c.comment },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.accent, undercurl = true },
    SpellLocal = { sp = c.cyan_dim, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },
    StatusLine = { fg = c.fg, bg = c.bg_status },
    StatusLineNC = { fg = c.comment_alt, bg = c.bg_status },
    Substitute = { fg = c.selection_fg, bg = c.magenta, bold = true },
    TabLine = { fg = c.comment_alt, bg = c.bg_status },
    TabLineFill = { fg = c.comment_alt, bg = c.bg_status },
    TabLineSel = { fg = c.selection_fg, bg = c.selection_bg, bold = true },
    Title = { fg = c.accent, bold = true },
    VertSplit = { fg = c.border },
    Visual = { fg = c.selection_fg, bg = c.selection_bg },
    VisualNOS = { fg = c.selection_fg, bg = c.selection_bg },
    WarningMsg = { fg = c.yellow },
    Whitespace = { fg = c.border },
    WildMenu = { fg = c.selection_fg, bg = c.selection_bg, bold = true },
    WinBar = { fg = c.fg, bg = c.bg },
    WinBarNC = { fg = c.comment_alt, bg = c.bg },
    WinSeparator = { fg = c.border_bright },

    DiagnosticDeprecated = { fg = c.comment_alt, strikethrough = true },
    DiagnosticUnnecessary = { fg = c.comment },
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.cyan_dim },
    DiagnosticHint = { fg = c.green },
    DiagnosticOk = { fg = c.green },
    DiagnosticSignError = { fg = c.red, bg = c.bg },
    DiagnosticSignWarn = { fg = c.yellow, bg = c.bg },
    DiagnosticSignInfo = { fg = c.cyan_dim, bg = c.bg },
    DiagnosticSignHint = { fg = c.green, bg = c.bg },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.bg_alt, italic = true },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.bg_alt, italic = true },
    DiagnosticVirtualTextInfo = { fg = c.cyan_dim, bg = c.bg_alt, italic = true },
    DiagnosticVirtualTextHint = { fg = c.green, bg = c.bg_alt, italic = true },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.cyan_dim, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.green, undercurl = true },

    DiffAdd = { fg = c.green, bg = c.bg_alt },
    DiffChange = { fg = c.accent, bg = c.bg_alt },
    DiffDelete = { fg = c.red, bg = c.bg_alt },
    DiffText = { fg = c.fg_bright, bg = c.bg_alt, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.accent },
    Removed = { fg = c.red },

    LspReferenceText = { bg = c.bg_alt },
    LspReferenceRead = { bg = c.bg_alt },
    LspReferenceWrite = { bg = c.selection_bg },
    LspCodeLens = { fg = c.comment },
    LspCodeLensSeparator = { fg = c.border },
    LspInlayHint = { fg = c.comment_alt, bg = c.bg_alt },

    TermCursor = { link = "Cursor" },
    TermCursorNC = { fg = c.selection_fg, bg = c.comment_alt },
  }
end

return M
