local M = {}

function M.get(c, opts)
  opts = opts or {}
  local comments_italic = opts.italic_comments ~= false

  return {
    Bold = { bold = true },
    Comment = { fg = c.comment, italic = comments_italic },
    Constant = { fg = c.yellow },
    String = { fg = c.green },
    Character = { fg = c.green_dim },
    Number = { fg = c.orange },
    Boolean = { fg = c.cyan_dim, bold = true },
    Float = { fg = c.orange },
    Identifier = { fg = c.fg },
    Function = { fg = c.accent },
    Statement = { fg = c.red },
    Conditional = { fg = c.red },
    Repeat = { fg = c.red_dim },
    Label = { fg = c.yellow },
    Operator = { fg = c.fg_muted },
    Keyword = { fg = c.accent_alt },
    Exception = { fg = c.red },
    PreProc = { fg = c.orange },
    Include = { fg = c.accent },
    Define = { fg = c.orange },
    Macro = { fg = c.orange },
    PreCondit = { fg = c.red_dim },
    Type = { fg = c.cyan },
    StorageClass = { fg = c.purple },
    Structure = { fg = c.orange },
    Typedef = { fg = c.cyan },
    Special = { fg = c.blue },
    SpecialChar = { fg = c.orange },
    Tag = { fg = c.accent },
    Delimiter = { fg = c.fg_muted },
    SpecialComment = { fg = c.comment_alt, italic = comments_italic },
    Debug = { fg = c.orange },
    Underlined = { fg = c.cyan_dim, underline = true },
    Ignore = { fg = c.comment },
    Italic = { italic = true },
    Error = { fg = c.red, bold = true },
    Strikethrough = { strikethrough = true },
    Todo = { fg = c.selection_fg, bg = c.selection_bg, bold = true },

    ["@annotation"] = { link = "PreProc" },
    ["@attribute"] = { fg = c.accent },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { fg = c.orange },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = c.comment_alt, italic = comments_italic },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.orange },
    ["@constant.macro"] = { fg = c.orange },
    ["@constructor"] = { fg = c.cyan },
    ["@diff.plus"] = { link = "DiffAdd" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.delta"] = { link = "DiffChange" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.accent_alt },
    ["@function.call"] = { fg = c.accent },
    ["@function.macro"] = { fg = c.orange },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { fg = c.accent_alt },
    ["@keyword.operator"] = { fg = c.accent_alt },
    ["@keyword.return"] = { fg = c.red_dim },
    ["@label"] = { link = "Label" },
    ["@markup.heading"] = { fg = c.accent, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.cyan_dim, underline = true },
    ["@markup.list"] = { fg = c.yellow },
    ["@markup.raw"] = { fg = c.green_dim },
    ["@markup.strong"] = { bold = true },
    ["@module"] = { fg = c.orange },
    ["@namespace"] = { fg = c.orange },
    ["@number"] = { link = "Number" },
    ["@operator"] = { link = "Operator" },
    ["@parameter"] = { fg = c.cyan },
    ["@property"] = { fg = c.fg },
    ["@punctuation.bracket"] = { fg = c.fg_muted },
    ["@punctuation.delimiter"] = { fg = c.fg_muted },
    ["@punctuation.special"] = { fg = c.orange },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.orange },
    ["@string.regex"] = { fg = c.green_dim },
    ["@tag"] = { fg = c.accent },
    ["@tag.attribute"] = { fg = c.yellow },
    ["@tag.delimiter"] = { fg = c.fg_muted },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.orange },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.orange },
    ["@variable.member"] = { fg = c.fg_muted },

    ["@lsp.type.class"] = { fg = c.cyan },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.decorator"] = { fg = c.orange },
    ["@lsp.type.enum"] = { fg = c.cyan },
    ["@lsp.type.enumMember"] = { fg = c.orange },
    ["@lsp.type.function"] = { fg = c.accent },
    ["@lsp.type.interface"] = { fg = c.orange },
    ["@lsp.type.keyword"] = { fg = c.accent_alt },
    ["@lsp.type.macro"] = { fg = c.orange },
    ["@lsp.type.method"] = { fg = c.accent_alt },
    ["@lsp.type.namespace"] = { fg = c.orange },
    ["@lsp.type.parameter"] = { fg = c.cyan },
    ["@lsp.type.property"] = { fg = c.fg_muted },
    ["@lsp.type.struct"] = { fg = c.cyan },
    ["@lsp.type.type"] = { fg = c.cyan },
    ["@lsp.type.typeParameter"] = { fg = c.yellow },
    ["@lsp.type.variable"] = { fg = c.fg },

  }
end

return M
